@extends('templates.york.blades.admin.layouts.admin')

@section('content')
    <div class="space-y-8 mb-12">
        {{-- ==================================================================================== --}}
        {{-- TOP HEADER --}}
        {{-- ==================================================================================== --}}
        <div class="flex flex-col md:flex-row justify-between items-start md:items-end gap-4 pb-2 border-b border-white/[0.06]">
            <div>
                <div class="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-cyan-500/10 border border-cyan-500/20 text-cyan-400 text-[10px] font-mono font-bold uppercase tracking-[0.25em] mb-2">
                    <span class="w-1.5 h-1.5 rounded-full bg-cyan-400 animate-pulse"></span>
                    {{ __('TRADE HISTORY') }}
                </div>
                <h1 class="text-2xl md:text-4xl font-black text-transparent bg-clip-text bg-gradient-to-r from-white via-cyan-100 to-cyan-400/70 tracking-tight leading-tight">
                    {{ __('Trading Bot History') }}
                </h1>
                <p class="text-slate-400 font-mono text-[10px] md:text-xs mt-0.5 tracking-widest uppercase">
                    {{ __('View all automated trades and profits generated by trading bots') }}
                </p>
            </div>

            {{-- Action Cluster --}}
            <div class="flex flex-wrap items-center gap-2.5 font-mono text-xs">
                <a href="{{ route('admin.trading-bots.index') }}"
                    class="px-4 py-2.5 rounded-xl bg-white/[0.03] hover:bg-white/[0.06] border border-white/[0.1] text-slate-300 hover:text-white font-bold uppercase tracking-wider transition-all flex items-center gap-2 cursor-pointer">
                    <svg class="w-4 h-4 text-cyan-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
                    </svg>
                    <span>{{ __('Trading Bots') }}</span>
                </a>

                <button type="button" onclick="openExportModal()"
                    class="px-4 py-2.5 rounded-xl bg-cyan-400 hover:bg-cyan-300 text-[#050507] font-black uppercase tracking-wider transition-all flex items-center gap-2 shadow-[0_0_20px_rgba(0,245,255,0.3)] cursor-pointer">
                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                    </svg>
                    <span>{{ __('Export') }}</span>
                </button>
            </div>
        </div>

        {{-- ==================================================================================== --}}
        {{-- 4-CARD STATS DECK --}}
        {{-- ==================================================================================== --}}
        <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            <div class="p-2 rounded-[2.5rem] bg-white/[0.02] border border-white/[0.08] backdrop-blur-2xl">
                <div class="rounded-[2rem] bg-[#090c14]/95 p-5 flex items-center justify-between font-mono">
                    <div>
                        <span class="text-[9px] uppercase font-bold text-slate-400 tracking-wider block mb-1">{{ __('Total Trading Volume') }}</span>
                        <span class="text-xl font-black text-white">{{ showAmount($stats['total_volume']) }}</span>
                    </div>
                    <div class="w-11 h-11 rounded-2xl bg-cyan-500/10 border border-cyan-500/20 text-cyan-400 flex items-center justify-center">
                        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6" />
                        </svg>
                    </div>
                </div>
            </div>

            <div class="p-2 rounded-[2.5rem] bg-white/[0.02] border border-white/[0.08] backdrop-blur-2xl">
                <div class="rounded-[2rem] bg-[#090c14]/95 p-5 flex items-center justify-between font-mono">
                    <div>
                        <span class="text-[9px] uppercase font-bold text-slate-400 tracking-wider block mb-1">{{ __('Total Profit Generated') }}</span>
                        <span class="text-xl font-black text-emerald-400">+{{ showAmount($stats['total_profit']) }}</span>
                    </div>
                    <div class="w-11 h-11 rounded-2xl bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 flex items-center justify-center">
                        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>
                    </div>
                </div>
            </div>

            <div class="p-2 rounded-[2.5rem] bg-white/[0.02] border border-white/[0.08] backdrop-blur-2xl">
                <div class="rounded-[2rem] bg-[#090c14]/95 p-5 flex items-center justify-between font-mono">
                    <div>
                        <span class="text-[9px] uppercase font-bold text-slate-400 tracking-wider block mb-1">{{ __('Total Trades') }}</span>
                        <span class="text-xl font-black text-purple-400">{{ number_format($stats['total_trades']) }}</span>
                    </div>
                    <div class="w-11 h-11 rounded-2xl bg-purple-500/10 border border-purple-500/20 text-purple-400 flex items-center justify-center">
                        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 3v2m6-2v2M9 19v2m6-2v2M5 9H3m2 6H3m18-6h-2m2 6h-2M7 19h10a2 2 0 002-2V7a2 2 0 00-2-2H7a2 2 0 00-2 2v10a2 2 0 002 2zM9 9h6v6H9V9z" />
                        </svg>
                    </div>
                </div>
            </div>

            <div class="p-2 rounded-[2.5rem] bg-white/[0.02] border border-white/[0.08] backdrop-blur-2xl">
                <div class="rounded-[2rem] bg-[#090c14]/95 p-5 flex items-center justify-between font-mono">
                    <div>
                        <span class="text-[9px] uppercase font-bold text-slate-400 tracking-wider block mb-1">{{ __('Win Rate') }}</span>
                        <span class="text-xl font-black text-cyan-300">{{ $stats['win_rate'] }}</span>
                    </div>
                    <div class="w-11 h-11 rounded-2xl bg-cyan-500/10 border border-cyan-500/20 text-cyan-400 flex items-center justify-center">
                        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>
                    </div>
                </div>
            </div>
        </div>

        {{-- ==================================================================================== --}}
        {{-- DATA TABLE CHASSIS (Double-Bezel) --}}
        {{-- ==================================================================================== --}}
        <div class="p-2 rounded-[2.5rem] bg-white/[0.02] border border-white/[0.1] backdrop-blur-2xl">
            <div class="rounded-[2rem] bg-[#090c14]/95 overflow-hidden font-mono">

                {{-- Table Toolbar --}}
                <div class="p-6 border-b border-white/[0.06] flex flex-col lg:flex-row justify-between items-center gap-4 text-xs">
                    <form action="{{ route('admin.trading-bots.logs.index') }}" method="GET" class="flex flex-wrap items-center gap-2.5 w-full lg:w-auto">
                        <input type="text" name="search" value="{{ request('search') }}" placeholder="{{ __('Search pair, bot or user...') }}" 
                            class="bg-[#05070d] border border-white/[0.1] focus:border-cyan-400 text-white rounded-xl px-4 py-2 text-xs focus:outline-none transition-all w-full sm:w-64">

                        <button type="submit" class="p-2 rounded-xl bg-cyan-400 text-black hover:bg-cyan-300 font-bold transition-all cursor-pointer">
                            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                            </svg>
                        </button>
                    </form>
                </div>

                {{-- Table Content --}}
                <div class="overflow-x-auto">
                    <table class="w-full text-left border-collapse text-xs">
                        <thead>
                            <tr class="bg-white/[0.02] border-b border-white/[0.06] text-[10px] text-slate-400 uppercase tracking-widest">
                                <th class="p-5">{{ __('User') }}</th>
                                <th class="p-5">{{ __('Trading Bot') }}</th>
                                <th class="p-5">{{ __('Trading Pair & Exchange') }}</th>
                                <th class="p-5 text-right">{{ __('Trade Amount') }}</th>
                                <th class="p-5 text-right">{{ __('Profit') }}</th>
                                <th class="p-5 text-right">{{ __('Trade Date') }}</th>
                            </tr>
                        </thead>
                        <tbody class="divide-y divide-white/[0.04]">
                            @forelse($logs as $log)
                                <tr class="hover:bg-white/[0.015] transition-colors group">
                                    {{-- User --}}
                                    <td class="p-5">
                                        <div class="flex items-center gap-3">
                                            <div class="w-8 h-8 rounded-xl bg-cyan-500/10 border border-cyan-500/20 text-cyan-400 flex items-center justify-center font-bold text-xs shrink-0">
                                                {{ substr($log->user?->username ?? 'U', 0, 2) }}
                                            </div>
                                            <div>
                                                <a href="{{ route('admin.users.detail', $log->user_id) }}" class="text-white hover:text-cyan-300 font-bold block leading-tight">
                                                    {{ $log->user?->fullname ?? $log->user?->username ?? 'N/A' }}
                                                </a>
                                                <span class="text-[10px] text-slate-500 block">@<span>{{ $log->user?->username ?? 'user' }}</span></span>
                                            </div>
                                        </div>
                                    </td>

                                    {{-- Bot --}}
                                    <td class="p-5">
                                        <span class="text-white font-bold block">{{ $log->activation?->bot?->name ?? 'N/A' }}</span>
                                        <span class="text-[10px] text-slate-400 uppercase">{{ $log->activation?->bot?->type ?? 'Crypto' }}</span>
                                    </td>

                                    {{-- Pair & Venue --}}
                                    <td class="p-5">
                                        <div class="flex items-center gap-2">
                                            <span class="px-2 py-0.5 rounded-md bg-cyan-500/10 text-cyan-300 border border-cyan-500/20 text-[10px] font-bold uppercase">
                                                {{ $log->pair }}
                                            </span>
                                            @if($log->exchange)
                                                <span class="text-[10px] text-slate-400">{{ $log->exchange }}</span>
                                            @endif
                                        </div>
                                    </td>

                                    {{-- Position Size --}}
                                    <td class="p-5 text-right text-slate-200 font-bold">
                                        {{ showAmount($log->amount) }}
                                    </td>

                                    {{-- Profit --}}
                                    <td class="p-5 text-right font-black text-emerald-400">
                                        +{{ showAmount($log->profit) }}
                                        <span class="text-[10px] block font-normal opacity-75">({{ number_format($log->profit_percentage, 2) }}%)</span>
                                    </td>

                                    {{-- Date --}}
                                    <td class="p-5 text-right text-slate-300 text-[11px]">
                                        {{ $log->created_at->format('M d, Y H:i:s') }}
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="6" class="p-12 text-center text-slate-500 font-mono">
                                        {{ __('No trade history found.') }}
                                    </td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>

                {{-- Pagination --}}
                @if($logs->hasPages())
                    <div class="p-6 border-t border-white/[0.06]">
                        {{ $logs->links('templates.york.blades.partials.pagination') }}
                    </div>
                @endif

            </div>
        </div>

    </div>

    {{-- Export Modal --}}
    <div id="exportModal" class="hidden fixed inset-0 bg-[#05070d]/90 backdrop-blur-xl z-[100] flex items-center justify-center p-4">
        <div class="p-2 rounded-[2.5rem] bg-white/[0.05] border border-white/[0.1] w-full max-w-md">
            <div class="rounded-[2rem] bg-[#090c14] p-8 space-y-6 font-mono">
                <div class="flex items-center justify-between pb-4 border-b border-white/[0.06]">
                    <h3 class="text-base font-bold text-white uppercase tracking-wide">{{ __('Export Trade History') }}</h3>
                    <button type="button" onclick="closeExportModal()" class="text-slate-400 hover:text-white text-lg cursor-pointer">&times;</button>
                </div>

                <div class="grid grid-cols-2 gap-2 text-xs" id="export-columns-container">
                    @foreach ([
                        'username' => 'User',
                        'bot_name' => 'Trading Bot',
                        'pair' => 'Trading Pair',
                        'exchange' => 'Exchange',
                        'amount' => 'Trade Amount',
                        'profit' => 'Profit Amount',
                        'profit_percentage' => 'Profit Percentage (%)',
                        'created_at' => 'Trade Date',
                    ] as $key => $label)
                        <label class="flex items-center gap-2.5 p-2 rounded-xl bg-white/[0.02] border border-white/[0.08] cursor-pointer hover:border-cyan-400/40">
                            <input type="checkbox" name="export_cols[]" value="{{ $key }}" checked 
                                class="w-3.5 h-3.5 rounded border-white/20 bg-white/5 text-cyan-400 accent-cyan-400 cursor-pointer">
                            <span class="text-slate-300 text-[11px]">{{ __($label) }}</span>
                        </label>
                    @endforeach
                </div>

                <div class="pt-4 border-t border-white/[0.06] grid grid-cols-3 gap-2 text-xs">
                    @foreach(['pdf' => 'PDF', 'csv' => 'CSV', 'sql' => 'SQL'] as $type => $label)
                        <button type="button" onclick="handleExport('{{ $type }}')" 
                            class="py-3 rounded-xl bg-white/[0.04] hover:bg-cyan-400 hover:text-black border border-white/[0.1] text-white font-bold uppercase tracking-wider transition-all cursor-pointer">
                            {{ $label }}
                        </button>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        function openExportModal() { $('#exportModal').removeClass('hidden'); }
        function closeExportModal() { $('#exportModal').addClass('hidden'); }

        function handleExport(type) {
            const selectedCols = [];
            $('input[name="export_cols[]"]:checked').each(function() {
                selectedCols.push($(this).val());
            });

            const currentUrl = new URL(window.location.href);
            const params = new URLSearchParams(currentUrl.search);
            params.set('export', type);
            if (selectedCols.length > 0) {
                params.set('columns', selectedCols.join(','));
            }

            window.location.href = "{{ route('admin.trading-bots.logs.index') }}?" + params.toString();
            closeExportModal();
        }
    </script>
@endpush
