<?php

namespace Database\Seeders;

use App\Models\TradingBot;
use Illuminate\Database\Seeder;

class TradingBotSeeder extends Seeder
{
    /**
     * Get the default list of 15 institutional trading bots.
     */
    public static function getDefaultBots(): array
    {
        return [
            [
                'name' => 'Nexus Arbitrage X',
                'logo' => 'nexus-arbitrage-x.svg',
                'type' => 'crypto',
                'exchanges' => ['Binance', 'Bybit', 'OKX'],
                'traded_pairs' => ['BTCUSDT', 'ETHUSDT', 'SOLUSDT'],
                'min_amount' => 250.00,
                'max_amount' => 25000.00,
                'is_active' => true,
                'daily_return_min' => 0.85,
                'daily_return_max' => 1.60,
                'duration' => 14,
                'duration_type' => 'day',
                'trading_days' => ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
                'is_capital_returned' => true,
            ],
            [
                'name' => 'Krypton Momentum Pulse',
                'logo' => 'krypton-momentum-pulse.svg',
                'type' => 'crypto',
                'exchanges' => ['Binance', 'Bybit', 'KuCoin'],
                'traded_pairs' => ['SOLUSDT', 'AVAXUSDT', 'NEARUSDT', 'DOTUSDT'],
                'min_amount' => 100.00,
                'max_amount' => 15000.00,
                'is_active' => true,
                'daily_return_min' => 1.20,
                'daily_return_max' => 2.40,
                'duration' => 7,
                'duration_type' => 'day',
                'trading_days' => ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
                'is_capital_returned' => true,
            ],
            [
                'name' => 'Vanguard Liquidity Harvester',
                'logo' => 'vanguard-liquidity-harvester.svg',
                'type' => 'crypto',
                'exchanges' => ['Binance', 'Bybit', 'OKX', 'Bitget'],
                'traded_pairs' => ['ETHUSDT', 'BTCUSDT', 'BNBUSDT', 'MATICUSDT'],
                'min_amount' => 1000.00,
                'max_amount' => 100000.00,
                'is_active' => true,
                'daily_return_min' => 0.90,
                'daily_return_max' => 1.85,
                'duration' => 30,
                'duration_type' => 'day',
                'trading_days' => ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
                'is_capital_returned' => true,
            ],
            [
                'name' => 'Specter Flash Scalper',
                'logo' => 'specter-flash-scalper.svg',
                'type' => 'crypto',
                'exchanges' => ['Binance', 'Bybit', 'Deribit'],
                'traded_pairs' => ['BTCUSDT', 'ETHUSDT', 'XRPUSDT'],
                'min_amount' => 50.00,
                'max_amount' => 5000.00,
                'is_active' => true,
                'daily_return_min' => 1.80,
                'daily_return_max' => 3.60,
                'duration' => 24,
                'duration_type' => 'hour',
                'trading_days' => ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
                'is_capital_returned' => true,
            ],
            [
                'name' => 'Zenith Quantitative Grid',
                'logo' => 'zenith-quantitative-grid.svg',
                'type' => 'crypto',
                'exchanges' => ['Binance', 'OKX', 'Gate.io'],
                'traded_pairs' => ['BTCUSDT', 'ETHUSDT', 'ADAUSDT', 'LINKUSDT'],
                'min_amount' => 500.00,
                'max_amount' => 50000.00,
                'is_active' => true,
                'daily_return_min' => 0.70,
                'daily_return_max' => 1.50,
                'duration' => 60,
                'duration_type' => 'day',
                'trading_days' => ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
                'is_capital_returned' => true,
            ],
            [
                'name' => 'Titanium Trend Sentinel',
                'logo' => 'titanium-trend-sentinel.svg',
                'type' => 'crypto',
                'exchanges' => ['Binance', 'Bybit', 'Kraken'],
                'traded_pairs' => ['BTCUSDT', 'ETHUSDT', 'SOLUSDT', 'XRPUSDT'],
                'min_amount' => 2500.00,
                'max_amount' => 250000.00,
                'is_active' => true,
                'daily_return_min' => 1.10,
                'daily_return_max' => 2.20,
                'duration' => 90,
                'duration_type' => 'day',
                'trading_days' => ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
                'is_capital_returned' => true,
            ],
            [
                'name' => 'Aether Yield Compounder',
                'logo' => 'aether-yield-compounder.svg',
                'type' => 'crypto',
                'exchanges' => ['Binance', 'Bybit', 'OKX', 'Deribit'],
                'traded_pairs' => ['BTCUSDT', 'ETHUSDT'],
                'min_amount' => 5000.00,
                'max_amount' => 500000.00,
                'is_active' => true,
                'daily_return_min' => 0.65,
                'daily_return_max' => 1.30,
                'duration' => 6,
                'duration_type' => 'month',
                'trading_days' => ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
                'is_capital_returned' => true,
            ],
            [
                'name' => 'Chronos Cycle Trader',
                'logo' => 'chronos-cycle-trader.svg',
                'type' => 'crypto',
                'exchanges' => ['Binance', 'Bybit'],
                'traded_pairs' => ['ETHUSDT', 'SOLUSDT', 'AVAXUSDT'],
                'min_amount' => 300.00,
                'max_amount' => 20000.00,
                'is_active' => true,
                'daily_return_min' => 1.05,
                'daily_return_max' => 2.15,
                'duration' => 21,
                'duration_type' => 'day',
                'trading_days' => ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
                'is_capital_returned' => true,
            ],
            [
                'name' => 'Hyperion Volume Surge',
                'logo' => 'hyperion-volume-surge.svg',
                'type' => 'crypto',
                'exchanges' => ['Binance', 'Bybit', 'OKX', 'Gate.io'],
                'traded_pairs' => ['BTCUSDT', 'DOGEUSDT', 'SHIBUSDT', 'PEPEUSDT'],
                'min_amount' => 150.00,
                'max_amount' => 10000.00,
                'is_active' => true,
                'daily_return_min' => 2.10,
                'daily_return_max' => 4.50,
                'duration' => 3,
                'duration_type' => 'day',
                'trading_days' => ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
                'is_capital_returned' => true,
            ],
            [
                'name' => 'Axiom Mean Reverter',
                'logo' => 'axiom-mean-reverter.svg',
                'type' => 'crypto',
                'exchanges' => ['Binance', 'Bybit', 'OKX'],
                'traded_pairs' => ['LTCUSDT', 'BCHUSDT', 'ETCUSDT', 'XLMUSDT'],
                'min_amount' => 200.00,
                'max_amount' => 25000.00,
                'is_active' => true,
                'daily_return_min' => 0.95,
                'daily_return_max' => 1.90,
                'duration' => 14,
                'duration_type' => 'day',
                'trading_days' => ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
                'is_capital_returned' => true,
            ],
            [
                'name' => 'Olympus FX Scalper',
                'logo' => 'olympus-fx-scalper.svg',
                'type' => 'forex',
                'exchanges' => null,
                'traded_pairs' => ['EURUSD', 'GBPUSD', 'USDJPY'],
                'min_amount' => 100.00,
                'max_amount' => 20000.00,
                'is_active' => true,
                'daily_return_min' => 0.80,
                'daily_return_max' => 1.70,
                'duration' => 5,
                'duration_type' => 'day',
                'trading_days' => ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
                'is_capital_returned' => true,
            ],
            [
                'name' => 'Sovereign Carry Alpha',
                'logo' => 'sovereign-carry-alpha.svg',
                'type' => 'forex',
                'exchanges' => null,
                'traded_pairs' => ['USDJPY', 'AUDJPY', 'NZDJPY', 'USDCHF'],
                'min_amount' => 3000.00,
                'max_amount' => 250000.00,
                'is_active' => true,
                'daily_return_min' => 0.50,
                'daily_return_max' => 1.15,
                'duration' => 4,
                'duration_type' => 'month',
                'trading_days' => ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
                'is_capital_returned' => true,
            ],
            [
                'name' => 'Aurum Gold Navigator',
                'logo' => 'aurum-gold-navigator.svg',
                'type' => 'forex',
                'exchanges' => null,
                'traded_pairs' => ['XAUUSD', 'XAGUSD'],
                'min_amount' => 500.00,
                'max_amount' => 100000.00,
                'is_active' => true,
                'daily_return_min' => 1.00,
                'daily_return_max' => 2.30,
                'duration' => 30,
                'duration_type' => 'day',
                'trading_days' => ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
                'is_capital_returned' => true,
            ],
            [
                'name' => 'Boreas Asian Range Breaker',
                'logo' => 'boreas-asian-range-breaker.svg',
                'type' => 'forex',
                'exchanges' => null,
                'traded_pairs' => ['USDJPY', 'AUDUSD', 'NZDUSD', 'EURJPY'],
                'min_amount' => 200.00,
                'max_amount' => 35000.00,
                'is_active' => true,
                'daily_return_min' => 0.90,
                'daily_return_max' => 1.95,
                'duration' => 10,
                'duration_type' => 'day',
                'trading_days' => ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
                'is_capital_returned' => true,
            ],
            [
                'name' => 'Atlas Macro Hedger',
                'logo' => 'atlas-macro-hedger.svg',
                'type' => 'forex',
                'exchanges' => null,
                'traded_pairs' => ['EURUSD', 'GBPUSD', 'USDCHF', 'USDCAD', 'AUDUSD'],
                'min_amount' => 10000.00,
                'max_amount' => 1000000.00,
                'is_active' => true,
                'daily_return_min' => 0.45,
                'daily_return_max' => 0.95,
                'duration' => 1,
                'duration_type' => 'year',
                'trading_days' => ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
                'is_capital_returned' => true,
            ],
        ];
    }

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        foreach (self::getDefaultBots() as $botData) {
            TradingBot::updateOrCreate(
                ['name' => $botData['name']],
                $botData
            );
        }
    }
}
